name: Weather ETL CI

# Trigger this action on push to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out your code
    - uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f etl/requirements.txt ]; then pip install -r etl/requirements.txt; fi

    # 4. Check for syntax errors (Linting)
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # 5. Run the test we created
    - name: Run Unit Tests
      working-directory: ./etl
      run: |
        python -m unittest test_weather.py